---
title: "Fantasy Football"
author: "Dusty Turner"
date: "9/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### gets and parses player data

```{r include=FALSE}
library(tidyverse)
base = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/"
year = "2019"
mid = "/segments/0/leagues/"
leagueID = "89417258"
tail = "?view=mMatchup&view=mMatchupScore"
url = paste0(base,year,mid,leagueID,tail)
ESPNGet <- httr::GET(url = url)
ESPNGet$status_code
ESPNRaw <- rawToChar(ESPNGet$content)
ESPNFromJSON <- jsonlite::fromJSON(ESPNRaw)
# ESPNFromJSON %>% listviewer::jsonedit()
# jsonlite::write_json(ESPNFromJSON,"SmallURLWeek1.JSON")
```



```{r}
## players on rosters
players = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>% map("player") %>%
  map_df(magrittr::extract,c("id","fullName","defaultPositionId")) %>%
  mutate(id = as.character(id))

## number of rows of stats for each player
observations = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>% map("player") %>% map("stats")  %>% 
  flatten() %>% map_df(~count(.)) 

playervec = 
players %>%
  mutate(observations = observations$n) %>%
  uncount(observations)

PositionDF = 
  tibble(PositionId = c(1,2,3,4,5,16),
         Position = c("Quarterback","Running Back","Wide Receiver","Tight End","Kicker","Defense"))

## projections and results for players withnames
playerperformance = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>% map("player") %>% map("stats")  %>% 
  flatten() %>% 
    map_df(magrittr::extract,c("scoringPeriodId","seasonId","statSourceId", "statSplitTypeId","id","externalId", "appliedTotal")) %>%
  mutate(Player = playervec$fullName) %>% 
  mutate(PositionId = playervec$defaultPositionId) %>% 
  left_join(PositionDF) 
  # filter(seasonId == 2019) 
  # as_tibble()  
  # write_csv("FF.csv")

playerperformance %>% arrange(desc(externalId)) %>% as_tibble() %>%
  filter(nchar(externalId)>5)

```

## gets team names and records

```{r}
library(tidyverse)

PlayerTeamDF = NULL

for (i in 1:2) {
  
base = "http://fantasy.espn.com/apis/v3/games/ffl/seasons/"
year = "2019"
mid = "/segments/0/leagues/"
leagueID = "89417258"
tail10 = "?view=mMatchup&view=mMatchupScore&scoringPeriodId="
tail = "?view=mDraftDetail&view=mLiveScoring&view=mMatchupScore&view=mPendingTransactions&view=mPositionalRatings&view=mSettings&view=mTeam&view=modular&view=mNav&view=mMatchupScore&scoringPeriodId="
url = paste0(base,year,mid,leagueID,tail,i)
url10 = paste0(base,year,mid,leagueID,tail10,i)

ESPNGet <- httr::GET(url = url)
ESPNGet$status_code
ESPNRaw <- rawToChar(ESPNGet$content)
ESPNFromJSON2 <- jsonlite::fromJSON(ESPNRaw)
# ESPNFromJSON2 %>% listviewer::jsonedit()

Sys.sleep(time = runif(1,2,4))

ESPNGet10 <- httr::GET(url = url10)
ESPNGet10$status_code
ESPNRaw10 <- rawToChar(ESPNGet10$content)
ESPNFromJSON10 <- jsonlite::fromJSON(ESPNRaw10)
# ESPNFromJSON10 %>% listviewer::jsonedit()

playerrosterslot = 
ESPNFromJSON10$teams$roster$entries %>% 
  map_df(`[`,"lineupSlotId") 

TeamPlayers = 
ESPNFromJSON$teams$roster$entries %>% map("playerPoolEntry") %>%
  map_df(~count(.)) 

PlayerTeamDFshort = 
ESPNFromJSON2$teams %>% select(location, nickname,id) %>%
  unite(Team, c(location,nickname)) %>%
  mutate(TeamPlayers = TeamPlayers$n) %>% 
  uncount(TeamPlayers) %>%
  mutate(Player = playerperformance$Player %>% unique()) %>%
  select(-id) %>% 
  mutate(playerrosterslot = playerrosterslot$lineupSlotId) %>%
  mutate(scoringPeriodId = i)

PlayerTeamDF = bind_rows(PlayerTeamDF,PlayerTeamDFshort)

}

```




```{r}

PlayerPerformance = 
playerperformance %>%
  left_join(PlayerTeamDF, by = c("Player","scoringPeriodId")) %>%
  as_tibble()


WeeklyEstimates = 
PlayerPerformance %>% 
  filter(nchar(externalId) > 4) %>%
  mutate(statSourceId = if_else(statSourceId==1, "Predicted", "Actual")) %>%
  select(scoringPeriodId,statSourceId,appliedTotal,Player,Position,Team,playerrosterslot) %>%
  spread(statSourceId, appliedTotal) %>% arrange(Player) %>%
  # filter(!is.na(Actual)) %>%
  mutate(ActualMinusPredicted = Actual-Predicted) 

WeeklyEstimates %>%
  arrange(Player) %>% 
  filter(Player=="Jordan Reed")

WeeklyEstimates %>%
  arrange(-ActualMinusPredicted) %>%
  group_by(Team, scoringPeriodId) %>%
  summarise(MeanActualMinusPredicted = mean(ActualMinusPredicted, na.rm = TRUE)) %>%
  arrange(scoringPeriodId)

```



